spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:192.168.100.82}:5432/${POSTGRES_DB:healthConnect}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASS:postgres}
