url=jdbc:postgresql://localhost:5432/healthConnect
username=postgres
password=postgres
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputChangeLogFile=src/main/resources/db/changelog/01-initial-schema.xml